version: "3.4"

x-defaults: &default
# 使用当前目录的 Dockerfile 来构建 docker 镜像
  restart: unless-stopped
  build: .
  volumes:
# 本文件存放于.devcontainer/中，因而此处要把上级目录(源代码目录)挂载到工作目录
    - ..:/home/sutd/projects/

services:
  aliancedb_u22_04_b-dev:
    <<: *default
    container_name: aliancedb_u22_04_b
    hostname: "aliancedb_u22_04_b"
# 如果在Dockerfile中修改过用户名，此处也要对应修改用户名和工作目录
    user: sutd
    working_dir: /home/sutd/projects/
    ports:
      - "127.0.0.1:2222:22"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
    privileged: true
# 同时通过 tailf 命令保持 container 不要退出的状态
    command:
      bash -c "service ssh restart && tail -f /dev/null"

